package com.h2o.ps360.dataobjects.sqldb;
/*
 * This is a Mariadb Entity where the acId and patientId are the same as patientId in 
 * Mongodb and For time being acId is also generated by the Programmer 
 */

import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
public class Patient {

	@Id
	public int acId;
	public int patientId;
	public String emailId;
	public String password;
	public byte isActive;

	public int getAcId() {
		return acId;
	}

	public void setAcId(int acId) {
		this.acId = acId;
	}

	public int getPatientId() {
		return patientId;
	}

	public void setPatientId(int patientId) {
		this.patientId = patientId;
	}

	public String getEmailId() {
		return emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public byte getIsActive() {
		return isActive;
	}

	public void setIsActive(byte isActive) {
		this.isActive = isActive;
	}

}
